"""Create initial tables

Revision ID: 76946a7d65e4
Revises: 
Create Date: 2025-10-21 11:30:51.813247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76946a7d65e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('Tag番号', sa.Integer(), nullable=False),
    sa.Column('説明', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Tag番号')
    )
    op.create_index(op.f('ix_Tag_Tag番号'), 'Tag', ['Tag番号'], unique=False)
    op.create_index(op.f('ix_Tag_説明'), 'Tag', ['説明'], unique=False)
    op.create_table('Todo',
    sa.Column('Todo番号', sa.Integer(), nullable=False),
    sa.Column('内容', sa.String(), nullable=True),
    sa.Column('期限', sa.String(), nullable=True),
    sa.Column('完了/未完了', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Todo番号')
    )
    op.create_index(op.f('ix_Todo_Todo番号'), 'Todo', ['Todo番号'], unique=False)
    op.create_index(op.f('ix_Todo_内容'), 'Todo', ['内容'], unique=False)
    op.create_table('設定',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.Tag番号'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['Todo.Todo番号'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_設定_id'), '設定', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_設定_id'), table_name='設定')
    op.drop_table('設定')
    op.drop_index(op.f('ix_Todo_内容'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_Todo番号'), table_name='Todo')
    op.drop_table('Todo')
    op.drop_index(op.f('ix_Tag_説明'), table_name='Tag')
    op.drop_index(op.f('ix_Tag_Tag番号'), table_name='Tag')
    op.drop_table('Tag')
    # ### end Alembic commands ###
